# This version contains a workaround for the Boost.Unordered file missing issue.
# Specifically, we download boost manually and include the path to $CMAKE_PREFIX_PATH
# so that cmake can find Boost.Unordered header files.
name: CI Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build and test
        run: |
          pushd /dev/shm
          wget -q https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2
          mkdir boost
          tar xf boost_1_87_0.tar.bz2 -C boost --strip-components 1
          export CPLUS_INCLUDE_PATH="${PWD}/boost"
          popd
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../ -DMETALLDATA_BUILD_TESTS=ON
          make -j6
          make test
          cd ../tests
          export OMPI_MCA_rmaps_base_oversubscribe=1
          bash run_test.sh
